name: Hello World Workflow

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the 'main' branch

jobs:
  say-hello:
    runs-on: ubuntu-latest  # Use an Ubuntu Linux runner

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

